### ISSUE TITLE
Error when using set_cover 

### ISSUE THREAD

**Issue by MissingNoIOI** [aerkalov/ebooklib#103]
Hi, 

I'm using Python 3.5 and when I try to set a cover, I get the following stacktrace:

```
Traceback (most recent call last):
  File "./main.py", line 181, in <module>
    main()
  File "./main.py", line 128, in main
    epub.write_epub(os.path.join(directory, bookname + ".epub"), book, {})
  File "/home/****/anaconda3/lib/python3.5/site-packages/ebooklib/epub.py", line 1163, in write_epub
    epub.write()
  File "/home/****/anaconda3/lib/python3.5/site-packages/ebooklib/epub.py", line 857, in write
    self._write_items()
  File "/home/****/anaconda3/lib/python3.5/site-packages/ebooklib/epub.py", line 848, in _write_items
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), item.get_content())
  File "/home/****/anaconda3/lib/python3.5/site-packages/ebooklib/epub.py", line 298, in get_content
    tree = parse_string(super(EpubCoverHtml, self).get_content())
  File "/home/****/anaconda3/lib/python3.5/site-packages/ebooklib/utils.py", line 30, in parse_string
    tree = etree.parse(io.BytesIO(s))
TypeError: a bytes-like object is required, not 'str'
```

The problem seems to be in line 456:

```
tree = parse_string(super(EpubCoverHtml, self).get_content())
```

`super(EpubCoverHtml, self).get_content()` simply returns an empty string, changing it to

```
tree = parse_string(super().get_content())
```

seems to work for me, although I'm not sure if it's  viable patch. On a sidenote, this error also appears when trying to execute sample number 2

**Comment by cedricvanrompay** [comment]
Same for me, however a bit different:

When executing ` ebooklib/samples/02_cover_create/create.py`:

```
$ python3 create.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ebooklib/utils.py", line 28, in parse_string
    tree = etree.parse(io.BytesIO(s.encode('utf-8')))
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1799, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124241)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:123074)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:117114)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111367)
lxml.etree.XMLSyntaxError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create.py", line 87, in <module>
    epub.write_epub('test.epub', book, {})
  File "/usr/local/lib/python3.5/dist-packages/ebooklib/epub.py", line 1163, in write_epub
    epub.write()
  File "/usr/local/lib/python3.5/dist-packages/ebooklib/epub.py", line 857, in write
    self._write_items()
  File "/usr/local/lib/python3.5/dist-packages/ebooklib/epub.py", line 848, in _write_items
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), item.get_content())
  File "/usr/local/lib/python3.5/dist-packages/ebooklib/epub.py", line 298, in get_content
    tree = parse_string(super(EpubCoverHtml, self).get_content())
  File "/usr/local/lib/python3.5/dist-packages/ebooklib/utils.py", line 30, in parse_string
    tree = etree.parse(io.BytesIO(s))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by YunTian5** [comment]
same for me.everybody know how to resolve it?

**Comment by Kennyl** [comment]
#92  monkey fix
but iBook prompt corrupted file when open, others or python2 won't .
