### ISSUE TITLE
cannot install pip install -Iv ebooklib==0.15

### ISSUE THREAD

**Issue by francesco1119** [aerkalov/ebooklib#141]
I'm trying to install a specific version of your library on Windows10 running `pip install -Iv ebooklib==0.15` but I receive as error: 

```
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting ebooklib==0.15
  1 location(s) to search for versions of ebooklib:
  * https://pypi.python.org/simple/ebooklib/
  Getting page https://pypi.python.org/simple/ebooklib/
  Looking up "https://pypi.python.org/simple/ebooklib/" in the cache
  Current age based on date: 1875
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/ebooklib/ HTTP/1.1" 200 381
  Updating cache with response from "https://pypi.python.org/simple/ebooklib/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/ebooklib/
    Found link https://pypi.python.org/packages/04/30/2cbf65fa9587a1ecc66a78eea91f9189ead8fdadd5e009115bce34529aa6/EbookLib-0.15.tar.gz#md5=d29882a04477c3854b1af9f6a84dc160 (from https://pypi.python.org/simple/ebooklib/), version: 0.15
    Found link https://pypi.python.org/packages/50/61/71082ffeeecdbdf7ded217b7bc439afa67563d8823f7bc5d4914232eb3f0/EbookLib-0.1.tar.gz#md5=cfa69e502e06d098b25285eaf2933eaa (from https://pypi.python.org/simple/ebooklib/), version: 0.1
    Found link https://pypi.python.org/packages/6d/4b/d432e26fd14cc8ad1bf86453261115127931312c7fda3eb0911efe67bed4/EbookLib-0.16.tar.gz#md5=ec0f12d312d5b055796a93085d483486 (from https://pypi.python.org/simple/ebooklib/), version: 0.16
  Using version 0.15 (newest of versions: 0.15)
  Looking up "https://pypi.python.org/packages/04/30/2cbf65fa9587a1ecc66a78eea91f9189ead8fdadd5e009115bce34529aa6/EbookLib-0.15.tar.gz" in the cache
  Current age based on date: 1904877
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 1904877
  Using cached EbookLib-0.15.tar.gz
  Downloading from URL https://pypi.python.org/packages/04/30/2cbf65fa9587a1ecc66a78eea91f9189ead8fdadd5e009115bce34529aa6/EbookLib-0.15.tar.gz#md5=d29882a04477c3854b1af9f6a84dc160 (from https://pypi.python.org/simple/ebooklib/)
  Running setup.py (path:C:\Users\franc\AppData\Local\Temp\pip-build-n2g_5rjh\ebooklib\setup.py) egg_info for package ebooklib
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\franc\AppData\Local\Temp\pip-build-n2g_5rjh\ebooklib\setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "c:\users\franc\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1671: character maps to <undefined>
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in C:\Users\franc\AppData\Local\Temp\pip-build-n2g_5rjh\ebooklib\
Exception information:
Traceback (most recent call last):
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\franc\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\franc\AppData\Local\Temp\pip-build-n2g_5rjh\ebooklib\
```

I'm running Python 3.6.3

**Comment by aerkalov** [comment]
Can you try 0.16 version. The problem was that README.md had some unicode characters inside.

**Comment by francesco1119** [comment]
...mmm...

I see... unfortunately in order to use [textract ](https://pypi.python.org/pypi/textract)I need Ebooklib 0.15 otherwise 0.16 is incompatible:

https://github.com/deanmalmgren/textract/issues/194

Yeah, this is not your problem, I understand... :( 

Thank you anyway

**Comment by Diana-uad** [comment]
I downloaded package from [`here`](https://pypi.org/project/EbookLib/0.15/#files).

1. Unpack it to a folder

1. 

1. 


Open file README.md
3.Save it as Unicode
4.Make a zip from that folder
5.Install like this
pip install your_path\EbookLib-0.15.zip

**Comment by Diana-uad** [comment]
I downloaded package from [here](https://pypi.org/project/EbookLib/0.15/#files).

1. Unpack it to a folder
2. Open file README.md
3. Save it as Unicode
4. Make a zip from that folder
5. Install like this
`pip install your_path\EbookLib-0.15.zip`

**Comment by aerkalov** [comment]
Closing this ticket due to no recent activity. Please let us know if you still require assistance. There are newer releases, hopefully there are no issues anymore. Managed to install v0.19 on Windows 10.
