### ISSUE TITLE
Ncx Nav write IndexError: tuple index out of range

### ISSUE THREAD

**Issue by CreativeMK** [aerkalov/ebooklib#167]
book.add_item(epub.EpubNcx())

Traceback (most recent call last):
  File "/Volumes/Data/Documents/Scripts/novel/light_novel.py", line 160, in <module>
    make_epub('https://www.lightnovel.cn/forum.php?mod=viewthread&tid=930679&page=1&authorid=540169')
  File "/Volumes/Data/Documents/Scripts/novel/light_novel.py", line 150, in make_epub
    epub.write_epub(title+'.epub', book, {})
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1612, in write_epub
    epub.write()
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1301, in write
    self._write_items()
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1286, in _write_items
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), self._get_ncx())
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1277, in _get_ncx
    _create_section(nav_map, self.book.toc, 0)
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1213, in _create_section
    section, subsection = item[0], item[1]
IndexError: tuple index out of range

        book.add_item(epub.EpubNav())

Traceback (most recent call last):
  File "/Volumes/Data/Documents/Scripts/novel/light_novel.py", line 160, in <module>
    make_epub('https://www.lightnovel.cn/forum.php?mod=viewthread&tid=930679&page=1&authorid=540169')
  File "/Volumes/Data/Documents/Scripts/novel/light_novel.py", line 150, in make_epub
    epub.write_epub(title+'.epub', book, {})
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1612, in write_epub
    epub.write()
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1301, in write
    self._write_items()
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1288, in _write_items
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), self._get_nav(item))
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1138, in _get_nav
    _create_section(nav, self.book.toc)
  File "/Volumes/Data/Documents/Scripts/novel/venv/lib/python3.6/site-packages/ebooklib/epub.py", line 1127, in _create_section
    _create_section(li, item[1])
IndexError: tuple index out of range

**Comment by aerkalov** [comment]
Can you paste the rest of the code? I am interested to see how you are creating TOC. Does sample file samples/01_basic_create/create.py fails for you?

**Comment by CreativeMK** [comment]
I'm sorry. I have deleted the old file and using a  module named 'mkepub' . 
As far as I remember, this program can correctly add items. 
In step of toc, errors didn't occur, as well as spine.
Most probably it is my code's error, but I just can't fix it out.
If more people have the same problem, may this can provide some help.

Thanks a lot for taking care my issue.

**Comment by aerkalov** [comment]
Yeah, most likely you did not define section in the format it expects it. I Would say you are missing this *(c1, c2)* part from the code sample.

This is example from the sample files:
```
book.toc = (
                     epub.Link('intro.xhtml', 'Introduction', 'intro'),
                      (
                         epub.Section('Languages'),
                           (c1, c2)
                       )
                )
```

When you insert a Section you insert it as a tuple/list element where first element is a Section object and the second one is tuple/list of pages. You can check it in samples/03_advanced_create/create.py file. Hope this helps.

**Comment by aerkalov** [comment]
Thanks! Will improve the docs :)
