### ISSUE TITLE
open / save book - got error

### ISSUE THREAD

**Issue by Shuraken007** [aerkalov/ebooklib#325]
Hi, can anybody check - is this library error, or mine local troubles?
I'm opening and saving epub book and got error
[book.epub.zip](https://github.com/user-attachments/files/17948614/book.epub.zip)

```
❯ python3 --version
Python 3.10.6

❯ poetry add git+https://github.com/aerkalov/ebooklib
❯ poetry run python3
>>> from ebooklib import epub
>>> book = epub.read_epub(name='input/book.epub', options={"ignore_ncx": True})
>>> epub.write_epub('output/book.epub', book)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.cache/pypoetry/virtualenvs/booktrans-QYQaQhuD-py3.10/lib/python3.10/site-packages/ebooklib/epub.py", line 1751, in write_epub
    epub.write()
  File "/home/alex/.cache/pypoetry/virtualenvs/booktrans-QYQaQhuD-py3.10/lib/python3.10/site-packages/ebooklib/epub.py", line 1374, in write
    self._write_items()
  File "/home/alex/.cache/pypoetry/virtualenvs/booktrans-QYQaQhuD-py3.10/lib/python3.10/site-packages/ebooklib/epub.py", line 1359, in _write_items
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), self._get_ncx())
  File "/home/alex/.cache/pypoetry/virtualenvs/booktrans-QYQaQhuD-py3.10/lib/python3.10/site-packages/ebooklib/epub.py", line 1350, in _get_ncx
    _create_section(nav_map, self.book.toc, 0)
  File "/home/alex/.cache/pypoetry/virtualenvs/booktrans-QYQaQhuD-py3.10/lib/python3.10/site-packages/ebooklib/epub.py", line 1310, in _create_section
    uid = _create_section(np, subsection, uid + 1)
  File "/home/alex/.cache/pypoetry/virtualenvs/booktrans-QYQaQhuD-py3.10/lib/python3.10/site-packages/ebooklib/epub.py", line 1319, in _create_section
    np = etree.SubElement(itm, 'navPoint', {'id': item.uid})
  File "src/lxml/etree.pyx", line 3205, in lxml.etree.SubElement
  File "src/lxml/apihelpers.pxi", line 206, in lxml.etree._makeSubElement
  File "src/lxml/apihelpers.pxi", line 201, in lxml.etree._makeSubElement
  File "src/lxml/apihelpers.pxi", line 325, in lxml.etree._initNodeAttributes
  File "src/lxml/apihelpers.pxi", line 336, in lxml.etree._addAttributeToNode
  File "src/lxml/apihelpers.pxi", line 1528, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

**Comment by Shuraken007** [comment]
`options={"ignore_ncx": True}` was a problem
