### ISSUE TITLE
Error to create cover

### ISSUE THREAD

**Issue by Criskanda** [aerkalov/ebooklib#90]
Just try to run the sample to create the cover, because my project does not work and I've noticed that when I download yours either, and just saw this error log, I use python 3.4, everything works correctly except cover.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/EbookLib-0.15-py3.4.egg/ebooklib/utils.py", line 28, in parse_string
  File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
  File "parser.pxi", line 1808, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106174)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95065)
lxml.etree.XMLSyntaxError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create.py", line 87, in <module>
    epub.write_epub('test.epub', book, {})
  File "/usr/local/lib/python3.4/site-packages/EbookLib-0.15-py3.4.egg/ebooklib/epub.py", line 1163, in write_epub
  File "/usr/local/lib/python3.4/site-packages/EbookLib-0.15-py3.4.egg/ebooklib/epub.py", line 857, in write
  File "/usr/local/lib/python3.4/site-packages/EbookLib-0.15-py3.4.egg/ebooklib/epub.py", line 848, in _write_items
  File "/usr/local/lib/python3.4/site-packages/EbookLib-0.15-py3.4.egg/ebooklib/epub.py", line 298, in get_content
  File "/usr/local/lib/python3.4/site-packages/EbookLib-0.15-py3.4.egg/ebooklib/utils.py", line 30, in parse_string
TypeError: 'str' does not support the buffer interface

**Comment by aerkalov** [comment]
I would say this was fixed with #92
